/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE public.operacion_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.operacion_id_seq IS 'Autogenerated Sequence.';

CREATE SEQUENCE public.tipo_operacion_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE public.tipo_operacion_id_seq IS 'Autogenerated Sequence.';




/************ Update: Tables ***************/

/******************** Add Table: public.operacion ************************/

/* Build Table Structure */
CREATE TABLE public.operacion
(
	id BIGINT DEFAULT nextval('public.operacion_id_seq'::regclass) NOT NULL,
	numero1 DECIMAL(30, 2) NOT NULL,
	numero2 DECIMAL(30, 2) NOT NULL,
	resultado DECIMAL(35, 2) NOT NULL,
	tipo_operacion_id BIGINT NOT NULL,
	fecha_creacion TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.operacion ADD CONSTRAINT pkoperacion
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON COLUMN public.operacion.id IS 'Llave primaria';

COMMENT ON COLUMN public.operacion.numero1 IS 'Contiene el número 1 de la operación';

COMMENT ON COLUMN public.operacion.numero2 IS 'Contiene el número 2 de la operación';

COMMENT ON COLUMN public.operacion.resultado IS 'Contiene el resultado de la operación';

COMMENT ON COLUMN public.operacion.tipo_operacion_id IS 'Llave primaria';

COMMENT ON COLUMN public.operacion.fecha_creacion IS 'Contiene la fecha de creación del registro';

COMMENT ON TABLE public.operacion IS 'Contiene el historial de operaciones realizadas';


/******************** Add Table: public.tipo_operacion ************************/

/* Build Table Structure */
CREATE TABLE public.tipo_operacion
(
	id BIGINT DEFAULT nextval('public.tipo_operacion_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(100) NULL,
	simbolo VARCHAR(1) NOT NULL,
	fecha_creacion TIMESTAMP NOT NULL,
	fecha_actualizacion TIMESTAMP NULL
) WITHOUT OIDS;

/* Add Primary Key */
ALTER TABLE public.tipo_operacion ADD CONSTRAINT pktipo_operacion
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON COLUMN public.tipo_operacion.id IS 'Llave primaria';

COMMENT ON COLUMN public.tipo_operacion.nombre IS 'Contiene el nombre';

COMMENT ON COLUMN public.tipo_operacion.simbolo IS 'Contiene el simbolo de la operacion';

COMMENT ON COLUMN public.tipo_operacion.fecha_creacion IS 'Contiene la fecha de creación del registro';

COMMENT ON COLUMN public.tipo_operacion.fecha_actualizacion IS 'Contiene la fecha de la actualización';

COMMENT ON TABLE public.tipo_operacion IS 'Contiene los tipos de operacion';





/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_operacion_tipo_operacion */
ALTER TABLE public.operacion ADD CONSTRAINT fk_operacion_tipo_operacion
	FOREIGN KEY (tipo_operacion_id) REFERENCES public.tipo_operacion (id)
	ON UPDATE NO ACTION ON DELETE NO ACTION;
	
INSERT INTO public.tipo_operacion
 (nombre, simbolo, fecha_creacion, fecha_actualizacion)
VALUES
     ('Multiplicación', 'x', now(), null);